#!/bin/bash

base_dir=$(dirname "${BASH_SOURCE[0]}")
prog_name=cloakbox

if [ "$1" == "setup" ]
then
	cd "$base_dir"

	mkdir -p "shared/openvpn"
	mkdir -p "shared/.$prog_name"
	mkdir -p "shared/downloads"
	rm -rf "shared/.$prog_name/setup_done"

	vagrant plugin install vagrant-vbguest
	vagrant plugin install vagrant-sshfs

	vagrant up --provision
	vagrant halt
elif [ "$1" == "start" ]
then
	if [ ! -f "$base_dir/shared/.$prog_name/setup_done" ]
	then
		"$0" setup
	fi
	cd "$base_dir"
	vagrant up
elif [ "$1" == "stop" ]
then
	cd "$base_dir"
	vagrant halt
elif [ "$1" == "updatevpn" ]
then
	if [ ! -f "$base_dir/shared/.$prog_name/setup_done" ]
	then
		"$0" setup
	fi
	# TODO mutex lock this command
	cd "$base_dir"
	vagrant up
	mkdir -p "shared/.$prog_name/tmp"
	rm -rf "shared/.$prog_name/tmp/openvpn"
	cp -r "openvpn" "shared/.$prog_name/tmp/openvpn"
	cmds_to_run=$(cat <<EOF
sudo service openvpn stop
cd /etc/openvpn
files=(*)
for file in "$files"
do
	if [ "$file" != "update-resolv-conf" ]
	then
		sudo rm -rf "$file"
	fi
done
sudo cp -n -t /etc/openvpn/ /shared/.$prog_name/tmp/openvpn/*
rm -rf /shared/.$prog_name/tmp/openvpn
sudo service openvpn start
EOF
	)
	echo "setting up openvpn inside of cloakbox"
	vagrant ssh -c "$cmds_to_run"
elif [ "$1" == "destroy" ]
then
	cd "$base_dir"
	vagrant destroy -f
	# TODO add a flag for also deleting the .vagrant folder
fi

