#!/bin/bash

base_dir=$(dirname "${BASH_SOURCE[0]}")
cd "$base_dir"

if [ "$1" == "setup" ]
then
	mkdir -p "shared"
	rm -rf "shared/.setup_done"
	vagrant plugin install vagrant-vbguest
	read -p "enter your PIA username: " pia_user
	read -p "enter your PIA password: " pia_pass
	mkdir -p "shared/tmp"
	echo "$pia_user" > "shared/tmp/.pia_credentials"
	echo "$pia_pass" >> "shared/tmp/.pia_credentials"
	vagrant reload --provision
	vagrant halt
elif [ "$1" == "start" ]
then
	if [ ! -f "shared/.setup_done" ]
	then
		"$0" setup
	fi
	vagrant up
elif [ "$1" == "stop" ]
then
	vagrant halt
fi
