#!/bin/bash

prog_name=cloakbox

mkdir -p "/etc/cloakbox"

echo "setting up openvpn"
openvpn_prefs=$(
	cat <<EOF
AUTOSTART="none"
OPTARGS=""
OMIT_SENDSIGS=0
EOF
)
echo "$openvpn_prefs" > /etc/default/openvpn
(
	cd /etc/openvpn
	files=(*)
	for file in "$files"
	do
		if [ "$file" != "update-resolv-conf" ]
		then
			rm -rf "$file"
		fi
	done
	cp -n -t /etc/openvpn/ /shared/openvpn/*
)

echo "setting up aria2"
rpc_secret=$(cat "/shared/.$prog_name/secret")
aria2_prefs=$(
{
	cat <<EOF
dir=/shared/downloads/
continue=true
always-resume=true
allow-overwrite=true
auto-save-interval=20
save-session-interval=20
daemon=true
enable-rpc=true
rpc-listen-port=6800
rpc-listen-all=true
rpc-save-upload-metadata=true
save-session=/shared/downloads/download_state
force-save=true
input-file=/shared/downloads/download_state
EOF
	# TODO escape rpc secret string in conf
	echo "rpc-secret=$rpc_secret"
})
mkdir -p "/etc/aria2"
echo "$aria2_prefs" > "/etc/aria2/aria2d.conf"

