#! /bin/sh
# /etc/init.d/aria2
 
### BEGIN INIT INFO
# Provides: aria2cRPC
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: aria2c RPC init script.
# Description: Starts and stops aria2 RPC services.
### END INIT INFO

. /lib/lsb/init-functions

RETVAL=0
case "$1" in
start)
	log_daemon_msg "Starting aria2c daemon"
	nohup start-stop-daemon --start --chuid "root" --exec "$(which aria2c)" -- --daemon --enable-rpc --conf-path="/etc/aria2/aria2d.conf"
	RETVAL=$?
	;;
stop)
	echo -n "Stopping aria2c daemon"
	start-stop-daemon --stop --oknodo --chuid "root" --exec "$(which aria2c)"
	RETVAL=$?
	;;
restart)
	stop
	start
	;;
*)
	echo $"Usage: $0 {start|stop|restart|status}"
	RETVAL=1
esac
exit $RETVAL

