#! /bin/sh
# /etc/init.d/aria2d
 
### BEGIN INIT INFO
# Provides: aria2cRPC
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: aria2c RPC init script.
# Description: Starts and stops aria2 RPC services.
### END INIT INFO

. /lib/lsb/init-functions

RETVAL=0
case "$1" in
start)
	log_daemon_msg "Starting aria2c daemon"
	nohup start-stop-daemon --start --chuid "root" --exec "$(which aria2c)" -- --daemon --enable-rpc --conf-path="/etc/aria2/aria2d.conf"
	RETVAL=$?
	;;
stop)
	forced=false
	arg_counter=2
	while [ $arg_counter -le $# ]
	do
		arg=${!$arg_counter}
		if [ "$arg" == "-f" ] || [ "$arg" == "--force" ]
		then
			forced=true
		else
			>&2 echo "invalid parameter $arg"
			exit 1
		fi
		arg_counter=$(($arg_counter+1))
	done
	if $forced
	then
		log_daemon_msg "Forcibly stopping aria2c daemon"
		start-stop-daemon --stop --oknodo --chuid "root" --signal 9 --exec "$(which aria2c)"
		RETVAL=$?
	else
		log_daemon_msg "Stopping aria2c daemon"
		start-stop-daemon --stop --oknodo --chuid "root" --retry 3 --exec "$(which aria2c)"
		RETVAL=$?
	fi
	;;
restart)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart|status}"
	RETVAL=1
esac
exit $RETVAL

