#!/bin/bash

prog_name=cloakbox

readonly EXITCODE_UNKNOWN_ERROR=1
readonly EXITCODE_BAD_ARGS=28

readonly EXITCODE_BAD_URL=101

readonly DOWNLOADS_ROOT="/shared/downloads"
readonly RPC_URL="http://localhost:6800/jsonrpc"

function json-escape
{
	json_str="$1"
	echo "${json_str,'"','\"'}"
}

function rpc-post-data
{
	escaped_method=$(json-escape "$1")
	echo "{\"jsonrpc\":\"2.0\", \"id\":\"$prog_name\", \"method\":\"$escaped_method\", \"params\":[$2]}"
}

if [ "$1" == "add" ]
then
	url="$2"
	if [ -z "$url" ]
	then
		>&2 echo "error: add requires a URL to be given"
		exit $EXITCODE_BAD_ARGS
	fi

	# Create a unique folder
	foldername=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32)
	while [ -d "$DOWNLOADS_ROOT/$foldername" ]
	do
		foldername=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32)
	done
	mkdir -p "$DOWNLOADS_ROOT/$foldername"

	# Make the request
	escaped_url=$(json-escape "$url")
	escaped_folderpath=$(json-escape "$DOWNLOADS_ROOT/$foldername")
	post_params="[\"$escaped_url\"], {\"dir\":\"$escaped_folderpath\"}"
	post_data=$(rpc-post-data "aria2.addUri" "$post_params")
	resp=$(wget -q -O - "$RPC_URL" --post-data="$post_data")

	if [ -z "$resp" ]
	then
		rm -rf "$DOWNLOADS_ROOT/$foldername"
		>&2 echo "Invalid URL"
		exit $EXITCODE_BAD_URL
	fi

	# Make another request to check the status of the download
	gid=$(echo "$resp" | jq -r ".result")
	escaped_gid=${gid//'"'/'\"'}
	post_data2=$(rpc-post-data "aria2.tellStatus" "\"$escaped_gid\"")
	resp2=$(wget -q -O - "$RPC_URL" --post-data="$post_data2")

	status=$(echo "$resp2" | jq -r ".result.status")
	if [ "$status" == "error" ]
	then
		# Remove the broken download and exit
		>&2 echo "Unable to start download"
		error_code=$(echo "$resp2" | jq -r ".result.errorCode")
		post_data3=$(rpc-post-data "aria2.remove" "\"$escaped_gid\"")
		wget -q "$RPC_URL" --post-data="$post_data3"
		rm -rf "$DOWNLOADS_ROOT/$foldername"
		exit "$errorCode"
	fi

	echo "Download added successfully"
	echo "GID: $gid"
	echo "path: $DOWNLOADS_ROOT/$foldername"
	echo "status: $status"
fi

